language: c

sudo: false

matrix:
  - os: linux
    sudo: false
  - os: osx
    before_install:
      - brew install bison
      - export PATH="/usr/local/opt/bison/bin:$PATH"

env:
  - MRUBY_CONFIG=travis_config.rb

script:
  - rake -m test:build && rake test:run

if: branch = master
on_success: change
on_failure: always
