language: c

sudo: false

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode7.1

env:
  - MRUBY_CONFIG=travis_config.rb
#script: "rake -m -E '$stdout.sync=true' all test"
#script: "rake -m && rake test"
script: "rake test"
