language: c

sudo: false

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode7.1

env:
  - MRUBY_CONFIG=travis_config.rb

script:
  - rake -m test:build && rake test:run

if: branch = master
on_success: change
on_failure: always
