name: CIFuzz
on: [push, pull_request]
jobs:
  Fuzzing:
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip gha]')
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'mruby'
          dry-run: false
      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'mruby'
          fuzz-seconds: 600
          dry-run: false
      - name: Upload Crash
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: artifacts
          path: ./out/artifacts
